# Generated by Django 4.1.4 on 2023-02-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
